Devise
rex-9/BlogValley pull request #9
Opened 2022-11-02 13:36 UTC by rex-9

- Removed `current_user` method in `ApplicationController`, devise will provide us with one.
- [Installed and setup devise](https://github.com/heartcombo/devise#getting-started).
  - Can register a new user.
  - User logs in with a combination of email and password.
  - Hashed password should be stored in the database.
  - Ask for confirmation of email.
  - Can reset password.
- [Modify the views in devise](https://github.com/heartcombo/devise#configuring-views) for registration and login to match [the wireframes from the Sneak Peek](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/sneak_peek.md#:~:text=For%20this%20project%20you%20will%20have%20full%20freedom%20in%20terms%20of%20visual%20design%20but%20you%20will%20need%20to%20keep%20the%20following%20wireframes%3A) and your styling.

2022-11-02 15:29 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @rex-9,

Nice job, you are almost there.

![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-11-02 15:29 UTC, omar-muhamad commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] Please add `:confirmable` module here to make the application asks for email confirmation.
See this [video](https://www.youtube.com/watch?v=nun18zM8Gq0) for more info.

2022-11-02 15:29 UTC, omar-muhamad commented on db/migrate/20221102083604_add_devise_to_users.rb
> +      # t.string   :unconfirmed_email # Only if using reconfirmable
- [ ] Kindly uncomment these records to activate email confirmation on your database and run the migration again to apply the changes.

2022-11-03 00:59 UTC, peterrobert commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
This change has been done well

2022-11-03 01:01 UTC, peterrobert commented on db/migrate/20221102083604_add_devise_to_users.rb
> +      # t.string   :unconfirmed_email # Only if using reconfirmable
This change has been done well

2022-11-03 01:05 UTC, peterrobert approved these changes
Hi @rex-9, 


### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 10:31 UTC, merged